### PR TITLE
Add st_is_polygon_cw and st_force_polygon_cw

### PR DESCRIPTION
**Pull request by ateucher**
PostGIS (via lwgeom) has [`ST_IsPolygonCW`](https://postgis.net/docs/ST_IsPolygonCW.html) and [`ST_ForcePolygonCW`](https://postgis.net/docs/ST_ForcePolygonCW.html) to check for and enforce the right-hand rule on polygons. This implements those functions as `st_is_polygon_cw()` and `st_force_polygon_cw()`. 

One thing in particular I wasn't sure about, as I am very inexperienced with `C++`, was the use of `lwgeom_free()`. I felt like it should have been in the loop [here](https://github.com/ateucher/lwgeom/blob/ae1a9558646de539ece5340eb344e549072493ef/src/lwgeom.cpp#L243) but I couldn't make it work. It works fine as it is but I don't know if there are consequences...

``` r
# devtools::install_github("ateucher/lwgeom", ref = "clockwise")
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.4, proj.4 5.0.1
library(lwgeom)
#> Linking to liblwgeom 2.4.4 r16526, GEOS 3.6.2, proj.4 5.0.1

polys <- st_as_sfc(c('POLYGON ((0 0, 1 0, 1 1, 0 0))', 
                     'POLYGON ((1 1, 2 2, 2 1, 1 1))'))

# Check the polygons - the first one has left-hand windings
st_is_polygon_cw(polys)
#> [1] FALSE  TRUE

# Fix them
ret <- st_force_polygon_cw(polys)

# check again
st_is_polygon_cw(ret)
#> [1] TRUE TRUE
```

Of course I realized after i did most of the work that `sf:::check_ring_dir()` exists, so 
decided to test the timing. The lwgeom function is quite a bit faster as seen below.

```r
# Test performance vs `sf:::check_ring_dir()`
library(microbenchmark)
test_polys <- st_as_sfc(rep(c('POLYGON ((0 0, 1 0, 1 1, 0 0))', 
                              'POLYGON ((1 1, 2 2, 2 1, 1 1))'), 1000))
microbenchmark(st_force_polygon_cw(test_polys), 
               sf:::check_ring_dir(test_polys))
#> Unit: milliseconds
#>                             expr       min       lq     mean   median
#>  st_force_polygon_cw(test_polys)  9.357423 10.37575 11.61274 11.37680
#>  sf:::check_ring_dir(test_polys) 52.599977 66.63510 70.99719 70.97328
#>        uq       max neval cld
#>  12.45239  16.74775   100  a 
#>  74.60841 112.34730   100   b
```

Created on 2018-05-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

### CODE REVIEW

**Comment by dbaston** [comment]
The call to `lwgeom_free` happens inside of `sfc_from_lwgeom`; you don't need to free the `LWGEOM` yourself.

**Comment by ateucher** [comment]
Ah, thanks @dbaston. So the errors I was generating were from it being called twice (the second time in `sfc_from_lwgeom`). And it works (and is necessary I assume) in `st_is_polygon_cw` and other functions that don't return an `sfc` object because they don't call `sfc_from_lwgeom`.

**Comment by edzer** [comment]
Great work, thanks! A good reason to clean up the sf side of handling ring directions. Will add you to the package contributors,

**Comment by ateucher** [comment]
Fantastic, thanks so much!

**Pull request merged**
