### PR TITLE
Bind st_astext from lwgeom

### PR DESCRIPTION
**Pull request by etiennebr**
Related: https://github.com/r-spatial/sf/issues/703

This will dramatically speedup the `WKT` conversion. I've used the postgis function names (`st_asewkb` and `st_astext`), I don't know if there is a convention to avoir collisions and keep compatibility with ISO and Postgis? 

Summary:
* adds `st_astext` and `st_asewkb` (I adapted the documentation from `sf::st_as_text`)
* enables `lwgeom_to_wkt` through `CPL_sfc_to_wkt`
* add RStudio files

### CODE REVIEW

**Comment by etiennebr** [comment]
@edzer if you agree with the PR, this would be ready to merge.

**Comment by edzer** [comment]
Looking good -- thanks!

**Comment by edzer** [comment]
I renamed argument precision to digits; let me know if you disagree.

**Comment by etiennebr** [comment]
Great! I'm sorry I thought I had renamed it. But maybe it was only in `sf`.

**Pull request merged**
