### PR TITLE
Ensure rwinlib compatibity with ucrt + some cleanup

### PR DESCRIPTION
**Pull request by jeroen**
Sync with https://github.com/r-spatial/sf/pull/1734 (I would recommend releasing these to CRAN approximately simultaneously)

### CODE REVIEW

**Comment by jeroen** [comment]
Do you mind if I clean up the CI a bit? R-3.6 is no longer supported on MacOS, and Ubuntu 16.04 is EOL as well.

**Comment by edzer** [comment]
That would be great!

**Comment by jeroen** [comment]
OK I have simplified the CI script such that it works on all platforms (incl Windows) and it should be more robust so you get less false positives.

**Comment by edzer** [comment]
Great, thanks a lot!

**Pull request merged**
