### PR TITLE
Tidy endpoint

### PR DESCRIPTION
**Pull request by Robinlovelace**
Heads-up @edzer it now works. This replaces https://github.com/r-spatial/lwgeom/pull/22

### CODE REVIEW

**Comment by Robinlovelace** [comment]
This is the same as #38 but without the merging commit so a little tidier. Take your pick + apologies for double PR.

**Comment by edzer** [comment]
Should I merge #38 or #39?

**Comment by Robinlovelace** [comment]
This one I suggest @edzer because it's a bit cleaner (has 1 less commit). They are identical in terms of code.

**Comment by edzer** [comment]
Thanks; it closed the other one automatically.

**Comment by edzer** [comment]
Thanks!

**Pull request merged**
